[package]
name = "mik32-rt"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv = { version = "*" }

# [build-dependencies]
# cc = "1.0"

[profile.release]
codegen-units = 1
debug = 2
debug-assertions = false
incremental = false
# lto = 'fat'
opt-level = 's'
overflow-checks = false
